import "server-only"
import { query } from "@/lib/db"
let ready:Promise<void>|undefined
export const eventDDL = [
  `CREATE TABLE IF NOT EXISTS erp_business_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id INT UNSIGNED NOT NULL, event_type VARCHAR(60) NOT NULL, schema_version INT NOT NULL DEFAULT 1, fanout_complete BOOLEAN NOT NULL DEFAULT 0, entity_id BIGINT UNSIGNED NOT NULL, event_key VARCHAR(191) NOT NULL, request_hash CHAR(64) NOT NULL, actor_id INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY event_identity(tenant_id,event_type,event_key), KEY tenant_idx(tenant_id,id)) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS erp_event_subscriptions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id INT UNSIGNED NOT NULL, name VARCHAR(120) NOT NULL, event_type VARCHAR(60) NOT NULL, config JSON NOT NULL, created_by INT UNSIGNED NOT NULL, enabled BOOLEAN NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, KEY route_idx(tenant_id,event_type,enabled)) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS erp_event_deliveries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id INT UNSIGNED NOT NULL, event_id BIGINT UNSIGNED NOT NULL, subscriber_id BIGINT UNSIGNED NOT NULL, config JSON NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'queued', attempts INT NOT NULL DEFAULT 0, available_at DATETIME NOT NULL, result_id BIGINT UNSIGNED NULL, error_code VARCHAR(80) NULL, completed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY delivery_identity(event_id,subscriber_id), KEY due_idx(status,available_at), KEY tenant_idx(tenant_id,event_id)) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS erp_event_delivery_log (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id INT UNSIGNED NOT NULL, delivery_id BIGINT UNSIGNED NOT NULL, action VARCHAR(40) NOT NULL, attempt INT NOT NULL, actor_id INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, KEY delivery_idx(tenant_id,delivery_id,id)) ENGINE=InnoDB`,
]
export function ensureEventSchema() {return ready ??= (async()=>{for(const ddl of eventDDL) await query(ddl)})().catch(e=>{ready=undefined;throw e})}
