"use client"

import Link from "next/link"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import { Eye, Loader2, MoreHorizontal, Plus, RefreshCw, ShieldCheck } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"

type Shopkeeper = { tenantId: number; businessName: string; ownerName: string | null; ownerEmail: string | null; ownerMobile: string | null; planName: string | null; subscriptionStatus: string | null; accountStatus: string; whatsappConnected: boolean; createdAt: string; lastLoginAt: string | null }

const initial = { businessName: "", displayName: "", businessMobile: "", country: "", timezone: "UTC", currency: "USD", ownerName: "", ownerEmail: "", ownerMobile: "", planCode: "", generatePassword: true, password: "", startTrial: false }

export function ShopkeeperManager({ shopkeepers, plans }: { shopkeepers: Shopkeeper[]; plans: { code: string; name: string }[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ ...initial, planCode: plans[0]?.code ?? "" }); const [pending, setPending] = useState(false); const [result, setResult] = useState<any>(null)
  const update = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }))
  async function create() { setPending(true); try { const res = await fetch("/api/platform/shopkeepers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const json = await res.json(); if (!res.ok) { toast.error(json.error || "Could not create shopkeeper"); return } setResult(json.shopkeeper); setOpen(false); router.refresh(); toast.success("Shopkeeper created") } catch { toast.error("Network error — please try again") } finally { setPending(false) } }
  async function setStatus(id: number, status: string) { setPending(true); try { const res = await fetch(`/api/platform/shopkeepers/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (!res.ok) throw new Error(); toast.success(`Shopkeeper ${status}`); router.refresh() } catch { toast.error("Could not update account") } finally { setPending(false) } }
  return <div className="flex flex-col gap-4">
    <div className="flex justify-end"><Button onClick={() => setOpen(true)}><Plus data-icon="inline-start" /> Add Shopkeeper</Button></div>
    <div className="overflow-hidden rounded-lg border bg-background"><Table><TableHeader><TableRow><TableHead>Shop / owner</TableHead><TableHead>Contact</TableHead><TableHead>Plan</TableHead><TableHead>Status</TableHead><TableHead>WhatsApp</TableHead><TableHead>Created</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{shopkeepers.length ? shopkeepers.map((shop) => <TableRow key={shop.tenantId}><TableCell><div className="flex flex-col"><Link className="font-medium hover:underline" href={`/platform/shopkeepers/${shop.tenantId}`}>{shop.businessName}</Link><span className="text-xs text-muted-foreground">{shop.ownerName || "No owner"} · #{shop.tenantId}</span></div></TableCell><TableCell><div className="flex flex-col text-sm"><span>{shop.ownerEmail || "—"}</span><span className="text-xs text-muted-foreground">{shop.ownerMobile || shop.ownerMobile || "—"}</span></div></TableCell><TableCell><div className="flex flex-col"><span>{shop.planName || "—"}</span><span className="text-xs capitalize text-muted-foreground">{shop.subscriptionStatus || "—"}</span></div></TableCell><TableCell><Badge variant={shop.accountStatus === "active" ? "default" : "destructive"} className="capitalize">{shop.accountStatus}</Badge></TableCell><TableCell><Badge variant="secondary">{shop.whatsappConnected ? "Connected" : "Not connected"}</Badge></TableCell><TableCell className="text-sm text-muted-foreground">{new Date(shop.createdAt).toLocaleDateString()}</TableCell><TableCell className="text-right"><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" disabled={pending}><MoreHorizontal /><span className="sr-only">Actions for {shop.businessName}</span></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link href={`/platform/shopkeepers/${shop.tenantId}`}><Eye /> View details</Link></DropdownMenuItem><DropdownMenuItem onClick={() => setStatus(shop.tenantId, shop.accountStatus === "active" ? "suspended" : "active")}><ShieldCheck /> {shop.accountStatus === "active" ? "Suspend" : "Activate"}</DropdownMenuItem><DropdownMenuItem onClick={() => router.push(`/platform/shopkeepers/${shop.tenantId}?reset=1`)}><RefreshCw /> Reset password</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>) : <TableRow><TableCell colSpan={7} className="h-32 text-center text-muted-foreground">No Shopkeeper customers yet.</TableCell></TableRow>}</TableBody></Table></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Add Shopkeeper</DialogTitle><DialogDescription>Create a tenant, owner login, subscription, and entitlements in one atomic operation.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="Shop / business name" value={form.businessName} onChange={(v) => update("businessName", v)} /><Field label="Display name" value={form.displayName} onChange={(v) => update("displayName", v)} /><Field label="Country" value={form.country} onChange={(v) => update("country", v)} /><Field label="Timezone" value={form.timezone} onChange={(v) => update("timezone", v)} /><Field label="Currency" value={form.currency} onChange={(v) => update("currency", v)} /><Field label="Business mobile" value={form.businessMobile} onChange={(v) => update("businessMobile", v)} /><Field label="Owner full name" value={form.ownerName} onChange={(v) => update("ownerName", v)} /><Field label="Owner email" type="email" value={form.ownerEmail} onChange={(v) => update("ownerEmail", v)} /><Field label="Owner mobile" value={form.ownerMobile} onChange={(v) => update("ownerMobile", v)} /><label className="flex flex-col gap-2 text-sm font-medium">Plan<select className="h-9 rounded-md border bg-background px-3 text-sm" value={form.planCode} onChange={(e) => update("planCode", e.target.value)}>{plans.map((p) => <option key={p.code} value={p.code}>{p.name}</option>)}</select></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={form.generatePassword} onChange={(e) => update("generatePassword", e.target.checked)} /> Generate secure temporary password</label>{!form.generatePassword && <Field label="Initial password" type="password" value={form.password} onChange={(v) => update("password", v)} />}</div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={create} disabled={pending || !form.planCode}>{pending && <Loader2 className="animate-spin" />} Create Shopkeeper</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(result)} onOpenChange={() => setResult(null)}><DialogContent><DialogHeader><DialogTitle>Shopkeeper Created Successfully</DialogTitle><DialogDescription>Save these credentials now. The temporary password will not be shown again.</DialogDescription></DialogHeader>{result && <div className="rounded-lg border bg-muted/30 p-4 text-sm"><p><strong>Business:</strong> {result.businessName}</p><p><strong>Owner:</strong> {result.ownerName}</p><p><strong>Login email:</strong> {result.ownerEmail}</p><p><strong>Temporary password:</strong> <code>{result.password}</code></p><p><strong>Tenant:</strong> {result.tenantId}</p><p><strong>Plan:</strong> {result.planName}</p></div>}<DialogFooter><Button onClick={() => navigator.clipboard?.writeText(`${result?.ownerEmail}\n${result?.password}`)}>Copy login details</Button><Button variant="outline" onClick={() => setResult(null)}>Done</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (v: string) => void; type?: string }) { return <label className="flex flex-col gap-2 text-sm font-medium">{label}<Input type={type} value={value} onChange={(e) => onChange(e.target.value)} required /></label> }
