CREATE TABLE IF NOT EXISTS message_permissions (id INT AUTO_INCREMENT PRIMARY KEY, employee_id INT NOT NULL, can_message_employees BOOLEAN NOT NULL DEFAULT TRUE, can_message_admins BOOLEAN NOT NULL DEFAULT TRUE, can_message_management BOOLEAN NOT NULL DEFAULT TRUE, allowed_department VARCHAR(120) NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_message_permission_employee (employee_id));
CREATE TABLE IF NOT EXISTS conversations (id INT AUTO_INCREMENT PRIMARY KEY, subject VARCHAR(200) NULL, created_by INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS conversation_participants (conversation_id INT NOT NULL, user_id INT NOT NULL, last_read_at DATETIME NULL, PRIMARY KEY (conversation_id, user_id));
CREATE TABLE IF NOT EXISTS messages (id INT AUTO_INCREMENT PRIMARY KEY, conversation_id INT NOT NULL, sender_id INT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_messages_conversation (conversation_id, created_at));
INSERT IGNORE INTO features (module_id,name,slug,description,sort_order) SELECT id,'Messages','messages.view','View and use internal messaging',90 FROM modules WHERE slug='messages';
INSERT IGNORE INTO features (module_id,name,slug,description,sort_order) SELECT id,'Message permissions','messages.manage_permissions','Manage employee messaging controls',91 FROM modules WHERE slug='messages';
INSERT IGNORE INTO features (module_id,name,slug,description,sort_order) SELECT id,'Messaging','messages.send','Send internal messages',92 FROM modules WHERE slug='messages';
ALTER TABLE messages ADD CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE conversation_participants ADD CONSTRAINT fk_cp_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
