CREATE TABLE IF NOT EXISTS mobile_app_releases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  application VARCHAR(64) NOT NULL,
  platform VARCHAR(24) NOT NULL,
  version_name VARCHAR(64) NOT NULL,
  version_code INT UNSIGNED NOT NULL,
  minimum_supported_version_code INT UNSIGNED NOT NULL,
  apk_url VARCHAR(2048) NULL,
  apk_url_hash CHAR(64) NULL,
  apk_size BIGINT UNSIGNED NULL,
  apk_sha256 CHAR(64) NULL,
  release_notes JSON NOT NULL,
  force_update TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('draft','published') NOT NULL DEFAULT 'draft',
  published_at DATETIME NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mobile_release_version (application, platform, version_code),
  UNIQUE KEY uq_mobile_release_apk_url_hash (apk_url_hash),
  KEY idx_mobile_release_latest (application, platform, status, version_code),
  CONSTRAINT fk_mobile_release_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_mobile_release_editor FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT ck_mobile_release_codes CHECK (version_code > 0 AND minimum_supported_version_code > 0 AND minimum_supported_version_code <= version_code),
  CONSTRAINT ck_mobile_release_published CHECK (status <> 'published' OR (apk_url IS NOT NULL AND apk_size > 0 AND apk_sha256 IS NOT NULL AND published_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
