-- Dedicated Finance sub-module tables.
--
-- The config-driven Finance modules (lib/finance-module-configs.ts + lib/finance-crud.ts)
-- read/write one dedicated table per module, but only the shared `finance_records`
-- table existed. This migration creates every table the CRUD factory targets, with
-- columns that match each ModuleConfig's field keys (and the pasted field spec) plus
-- the system columns the factory writes: created_by, created_at, updated_at, and the
-- tracking columns (tracking_id / opened / open_count) for modules with trackingId.
--
-- Column type conventions (mirrors 2026-09-06-add-sales-invoices.sql):
--   ids .................. VARCHAR(40)
--   names ................ VARCHAR(190)
--   money / amounts ...... DECIMAL(14,2)
--   percentages / rates .. DECIMAL(6,2)
--   checkboxes ........... TINYINT(1) DEFAULT 0
--   selects / short text . VARCHAR(40-120)
--   long text ............ TEXT

-- ---------------------------------------------------------------------------
-- 1. Purchase Bills  (manual PO Number id)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_bills (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  po_number VARCHAR(60) NOT NULL,
  bill_date DATE DEFAULT NULL,
  bill_type VARCHAR(40) DEFAULT NULL,
  financial_year VARCHAR(12) DEFAULT NULL,
  vendor_id VARCHAR(40) DEFAULT NULL,
  vendor_name VARCHAR(190) DEFAULT NULL,
  project_id VARCHAR(40) DEFAULT NULL,
  project_name VARCHAR(190) DEFAULT NULL,
  description TEXT,
  hsn_sac VARCHAR(20) DEFAULT NULL,
  quantity DECIMAL(14,2) NOT NULL DEFAULT 0,
  unit VARCHAR(20) DEFAULT NULL,
  rate DECIMAL(14,2) NOT NULL DEFAULT 0,
  taxable_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  discount DECIMAL(14,2) NOT NULL DEFAULT 0,
  cgst_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
  sgst_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
  igst_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
  other_tax_cess DECIMAL(14,2) NOT NULL DEFAULT 0,
  cgst_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  sgst_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  igst_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  gross_bill_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  tds_applicable TINYINT(1) NOT NULL DEFAULT 0,
  tds_section VARCHAR(20) DEFAULT NULL,
  tds_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
  tds_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  net_payable DECIMAL(14,2) NOT NULL DEFAULT 0,
  outstanding_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  due_date DATE DEFAULT NULL,
  amount_paid DECIMAL(14,2) NOT NULL DEFAULT 0,
  payment_status VARCHAR(30) NOT NULL DEFAULT 'Unpaid',
  payment_date DATE DEFAULT NULL,
  payment_reference VARCHAR(120) DEFAULT NULL,
  itc_eligible TINYINT(1) NOT NULL DEFAULT 0,
  itc_claimed TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_purchase_po (po_number),
  KEY idx_pb_date (bill_date),
  KEY idx_pb_fy (financial_year),
  KEY idx_pb_vendor (vendor_name),
  KEY idx_pb_status (payment_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 2. Expenses  (EXP-#### id)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  expense_id VARCHAR(40) NOT NULL,
  expense_date DATE DEFAULT NULL,
  expense_type VARCHAR(40) DEFAULT NULL,
  financial_year VARCHAR(12) DEFAULT NULL,
  party_id VARCHAR(40) DEFAULT NULL,
  party_name VARCHAR(190) DEFAULT NULL,
  project_id VARCHAR(40) DEFAULT NULL,
  project_name VARCHAR(190) DEFAULT NULL,
  expense_category VARCHAR(120) DEFAULT NULL,
  expense_head VARCHAR(120) DEFAULT NULL,
  description TEXT,
  bill_receipt_no VARCHAR(80) DEFAULT NULL,
  payment_mode VARCHAR(40) DEFAULT NULL,
  bank_cash_account_id VARCHAR(40) DEFAULT NULL,
  taxable_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  cgst_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  sgst_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  igst_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  tds_applicable TINYINT(1) NOT NULL DEFAULT 0,
  tds_section VARCHAR(20) DEFAULT NULL,
  tds_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
  tds_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  gross_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  net_payable DECIMAL(14,2) NOT NULL DEFAULT 0,
  approval_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  approved_by VARCHAR(190) DEFAULT NULL,
  reimbursement_status VARCHAR(30) DEFAULT NULL,
  payment_date DATE DEFAULT NULL,
  payment_reference VARCHAR(120) DEFAULT NULL,
  gst_credit_eligible TINYINT(1) NOT NULL DEFAULT 0,
  cost_centre VARCHAR(120) DEFAULT NULL,
  notes TEXT,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_expense_id (expense_id),
  KEY idx_exp_date (expense_date),
  KEY idx_exp_fy (financial_year),
  KEY idx_exp_party (party_name),
  KEY idx_exp_status (approval_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 3. FTE Invoices  (FTE-#### id, tracking enabled)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fte_invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  fte_invoice_id VARCHAR(40) NOT NULL,
  invoice_date DATE DEFAULT NULL,
  financial_year VARCHAR(12) DEFAULT NULL,
  month VARCHAR(20) DEFAULT NULL,
  employee_id VARCHAR(40) DEFAULT NULL,
  employee_name VARCHAR(190) DEFAULT NULL,
  employment_type VARCHAR(40) DEFAULT NULL,
  department VARCHAR(120) DEFAULT NULL,
  designation VARCHAR(120) DEFAULT NULL,
  project_id VARCHAR(40) DEFAULT NULL,
  project_name VARCHAR(190) DEFAULT NULL,
  billing_basis VARCHAR(40) DEFAULT NULL,
  working_days DECIMAL(6,2) NOT NULL DEFAULT 0,
  paid_days DECIMAL(6,2) NOT NULL DEFAULT 0,
  leave_days DECIMAL(6,2) NOT NULL DEFAULT 0,
  holiday_days DECIMAL(6,2) NOT NULL DEFAULT 0,
  gross_billing DECIMAL(14,2) NOT NULL DEFAULT 0,
  overtime_extra DECIMAL(14,2) NOT NULL DEFAULT 0,
  bonus_incentive DECIMAL(14,2) NOT NULL DEFAULT 0,
  other_earnings DECIMAL(14,2) NOT NULL DEFAULT 0,
  gross_earnings DECIMAL(14,2) NOT NULL DEFAULT 0,
  pf_deduction DECIMAL(14,2) NOT NULL DEFAULT 0,
  esi_deduction DECIMAL(14,2) NOT NULL DEFAULT 0,
  professional_tax DECIMAL(14,2) NOT NULL DEFAULT 0,
  tds DECIMAL(14,2) NOT NULL DEFAULT 0,
  other_deductions DECIMAL(14,2) NOT NULL DEFAULT 0,
  total_deductions DECIMAL(14,2) NOT NULL DEFAULT 0,
  net_payable DECIMAL(14,2) NOT NULL DEFAULT 0,
  payment_due_date DATE DEFAULT NULL,
  payment_date DATE DEFAULT NULL,
  payment_reference VARCHAR(120) DEFAULT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Draft',
  notes TEXT,
  tracking_id VARCHAR(64) DEFAULT NULL,
  opened TINYINT(1) NOT NULL DEFAULT 0,
  first_opened_on TIMESTAMP NULL DEFAULT NULL,
  last_opened_on TIMESTAMP NULL DEFAULT NULL,
  open_count INT NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_fte_invoice_id (fte_invoice_id),
  KEY idx_fte_date (invoice_date),
  KEY idx_fte_fy (financial_year),
  KEY idx_fte_employee (employee_name),
  KEY idx_fte_status (status),
  KEY idx_fte_tracking (tracking_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 4. Freelance Invoices  (FRL-#### id, tracking enabled)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS freelance_invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  freelance_invoice_id VARCHAR(40) NOT NULL,
  invoice_date DATE DEFAULT NULL,
  financial_year VARCHAR(12) DEFAULT NULL,
  billing_period VARCHAR(60) DEFAULT NULL,
  freelancer_id VARCHAR(40) DEFAULT NULL,
  freelancer_name VARCHAR(190) DEFAULT NULL,
  project_id VARCHAR(40) DEFAULT NULL,
  project_name VARCHAR(190) DEFAULT NULL,
  work_description TEXT,
  units_deliverables DECIMAL(14,2) NOT NULL DEFAULT 0,
  unit VARCHAR(20) DEFAULT NULL,
  rate DECIMAL(14,2) NOT NULL DEFAULT 0,
  gross_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  tds_applicable TINYINT(1) NOT NULL DEFAULT 0,
  tds_section VARCHAR(20) DEFAULT NULL,
  tds_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
  tds_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  other_adjustment DECIMAL(14,2) NOT NULL DEFAULT 0,
  net_payable DECIMAL(14,2) NOT NULL DEFAULT 0,
  invoice_bill_reference VARCHAR(120) DEFAULT NULL,
  due_date DATE DEFAULT NULL,
  payment_date DATE DEFAULT NULL,
  payment_reference VARCHAR(120) DEFAULT NULL,
  payment_status VARCHAR(30) NOT NULL DEFAULT 'Unpaid',
  approval_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  notes TEXT,
  tracking_id VARCHAR(64) DEFAULT NULL,
  opened TINYINT(1) NOT NULL DEFAULT 0,
  first_opened_on TIMESTAMP NULL DEFAULT NULL,
  last_opened_on TIMESTAMP NULL DEFAULT NULL,
  open_count INT NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_freelance_invoice_id (freelance_invoice_id),
  KEY idx_frl_date (invoice_date),
  KEY idx_frl_fy (financial_year),
  KEY idx_frl_freelancer (freelancer_name),
  KEY idx_frl_status (payment_status),
  KEY idx_frl_tracking (tracking_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 5. Bank Transactions  (BTX-#### id)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bank_transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  transaction_id VARCHAR(40) NOT NULL,
  transaction_date DATE DEFAULT NULL,
  value_date DATE DEFAULT NULL,
  financial_year VARCHAR(12) DEFAULT NULL,
  month VARCHAR(20) DEFAULT NULL,
  bank_cash_account_id VARCHAR(40) DEFAULT NULL,
  account_name VARCHAR(190) DEFAULT NULL,
  transaction_type VARCHAR(40) DEFAULT NULL,
  voucher_type VARCHAR(40) DEFAULT NULL,
  reference_no VARCHAR(80) DEFAULT NULL,
  party_id VARCHAR(40) DEFAULT NULL,
  party_name VARCHAR(190) DEFAULT NULL,
  account_head_id VARCHAR(40) DEFAULT NULL,
  account_head VARCHAR(120) DEFAULT NULL,
  project_id VARCHAR(40) DEFAULT NULL,
  project_name VARCHAR(190) DEFAULT NULL,
  debit DECIMAL(14,2) NOT NULL DEFAULT 0,
  credit DECIMAL(14,2) NOT NULL DEFAULT 0,
  amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  gst_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  tds_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  payment_mode VARCHAR(40) DEFAULT NULL,
  cheque_utr_reference VARCHAR(120) DEFAULT NULL,
  narration TEXT,
  reconciliation_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  reconciliation_date DATE DEFAULT NULL,
  journal_entry_id VARCHAR(40) DEFAULT NULL,
  attachment_link VARCHAR(255) DEFAULT NULL,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_bank_transaction_id (transaction_id),
  KEY idx_btx_date (transaction_date),
  KEY idx_btx_fy (financial_year),
  KEY idx_btx_account (account_name),
  KEY idx_btx_status (reconciliation_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 6. Bank & Cash accounts  (ACC-#### id)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  finance_account_id VARCHAR(40) NOT NULL,
  account_name VARCHAR(190) DEFAULT NULL,
  account_type VARCHAR(40) DEFAULT NULL,
  bank_name VARCHAR(190) DEFAULT NULL,
  branch VARCHAR(190) DEFAULT NULL,
  account_number VARCHAR(60) DEFAULT NULL,
  ifsc VARCHAR(15) DEFAULT NULL,
  upi_wallet_id VARCHAR(120) DEFAULT NULL,
  currency VARCHAR(10) DEFAULT NULL,
  opening_balance DECIMAL(14,2) NOT NULL DEFAULT 0,
  opening_balance_date DATE DEFAULT NULL,
  current_book_balance DECIMAL(14,2) NOT NULL DEFAULT 0,
  bank_statement_balance DECIMAL(14,2) NOT NULL DEFAULT 0,
  difference DECIMAL(14,2) NOT NULL DEFAULT 0,
  reconciliation_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  last_reconciliation_date DATE DEFAULT NULL,
  primary_account TINYINT(1) NOT NULL DEFAULT 0,
  active_status VARCHAR(20) NOT NULL DEFAULT 'Active',
  remarks TEXT,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_account_id (finance_account_id),
  KEY idx_facc_name (account_name),
  KEY idx_facc_status (reconciliation_status),
  KEY idx_facc_active (active_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 7. Chart of Accounts  (COA-#### id)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chart_of_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  account_id VARCHAR(40) NOT NULL,
  account_code VARCHAR(40) DEFAULT NULL,
  account_name VARCHAR(190) DEFAULT NULL,
  account_group VARCHAR(80) DEFAULT NULL,
  account_type VARCHAR(80) DEFAULT NULL,
  parent_account_id VARCHAR(40) DEFAULT NULL,
  nature VARCHAR(40) DEFAULT NULL,
  opening_balance DECIMAL(14,2) NOT NULL DEFAULT 0,
  opening_balance_type VARCHAR(20) DEFAULT NULL,
  gst_applicable TINYINT(1) NOT NULL DEFAULT 0,
  tds_applicable TINYINT(1) NOT NULL DEFAULT 0,
  tax_category VARCHAR(80) DEFAULT NULL,
  bank_cash_account TINYINT(1) NOT NULL DEFAULT 0,
  reconciliation_required TINYINT(1) NOT NULL DEFAULT 0,
  active_status VARCHAR(20) NOT NULL DEFAULT 'Active',
  effective_from DATE DEFAULT NULL,
  effective_to DATE DEFAULT NULL,
  remarks TEXT,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_coa_account_id (account_id),
  KEY idx_coa_code (account_code),
  KEY idx_coa_name (account_name),
  KEY idx_coa_type (account_type),
  KEY idx_coa_active (active_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 8. Customers / Vendors  (CV-#### id)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers_vendors (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  party_id VARCHAR(40) NOT NULL,
  customer_name VARCHAR(190) DEFAULT NULL,
  legal_name VARCHAR(190) DEFAULT NULL,
  party_type VARCHAR(40) DEFAULT NULL,
  party_category VARCHAR(80) DEFAULT NULL,
  gstin VARCHAR(20) DEFAULT NULL,
  pan VARCHAR(15) DEFAULT NULL,
  tan VARCHAR(15) DEFAULT NULL,
  contact_person VARCHAR(190) DEFAULT NULL,
  official_email VARCHAR(190) DEFAULT NULL,
  invoice_email VARCHAR(190) DEFAULT NULL,
  alternate_email VARCHAR(190) DEFAULT NULL,
  mobile VARCHAR(30) DEFAULT NULL,
  alternate_mobile VARCHAR(30) DEFAULT NULL,
  billing_address TEXT,
  city VARCHAR(120) DEFAULT NULL,
  state VARCHAR(120) DEFAULT NULL,
  state_code VARCHAR(6) DEFAULT NULL,
  pin_code VARCHAR(12) DEFAULT NULL,
  country VARCHAR(80) DEFAULT NULL,
  payment_terms_days VARCHAR(40) DEFAULT NULL,
  credit_limit DECIMAL(14,2) NOT NULL DEFAULT 0,
  currency VARCHAR(10) DEFAULT NULL,
  bank_name VARCHAR(190) DEFAULT NULL,
  bank_branch VARCHAR(190) DEFAULT NULL,
  bank_account_no VARCHAR(60) DEFAULT NULL,
  ifsc VARCHAR(15) DEFAULT NULL,
  account_holder_name VARCHAR(190) DEFAULT NULL,
  tds_section VARCHAR(20) DEFAULT NULL,
  tds_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
  gst_registration_type VARCHAR(40) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  notes TEXT,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cv_party_id (party_id),
  KEY idx_cv_name (customer_name),
  KEY idx_cv_gstin (gstin),
  KEY idx_cv_pan (pan),
  KEY idx_cv_city (city),
  KEY idx_cv_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 9. GST Filings  (GST-#### id)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gst_filings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  gst_filing_id VARCHAR(40) NOT NULL,
  financial_year VARCHAR(12) DEFAULT NULL,
  return_period VARCHAR(40) DEFAULT NULL,
  gstin VARCHAR(20) DEFAULT NULL,
  legal_name VARCHAR(190) DEFAULT NULL,
  return_type VARCHAR(40) DEFAULT NULL,
  filing_frequency VARCHAR(40) DEFAULT NULL,
  filing_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  due_date DATE DEFAULT NULL,
  invoice_type VARCHAR(40) DEFAULT NULL,
  supply_category VARCHAR(80) DEFAULT NULL,
  recipient_gstin VARCHAR(20) DEFAULT NULL,
  recipient_name VARCHAR(190) DEFAULT NULL,
  name_as_in_master VARCHAR(190) DEFAULT NULL,
  invoice_number VARCHAR(80) DEFAULT NULL,
  invoice_date DATE DEFAULT NULL,
  total_invoice_value DECIMAL(14,2) NOT NULL DEFAULT 0,
  place_of_supply VARCHAR(80) DEFAULT NULL,
  supply_type VARCHAR(40) DEFAULT NULL,
  tax_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
  taxable_value DECIMAL(14,2) NOT NULL DEFAULT 0,
  cess_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  igst DECIMAL(14,2) NOT NULL DEFAULT 0,
  cgst DECIMAL(14,2) NOT NULL DEFAULT 0,
  sgst DECIMAL(14,2) NOT NULL DEFAULT 0,
  total_tax DECIMAL(14,2) NOT NULL DEFAULT 0,
  itc_eligible TINYINT(1) NOT NULL DEFAULT 0,
  itc_igst DECIMAL(14,2) NOT NULL DEFAULT 0,
  itc_cgst DECIMAL(14,2) NOT NULL DEFAULT 0,
  itc_sgst DECIMAL(14,2) NOT NULL DEFAULT 0,
  itc_cess DECIMAL(14,2) NOT NULL DEFAULT 0,
  itc_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  itc_reversal DECIMAL(14,2) NOT NULL DEFAULT 0,
  net_itc DECIMAL(14,2) NOT NULL DEFAULT 0,
  tds DECIMAL(14,2) NOT NULL DEFAULT 0,
  tcs DECIMAL(14,2) NOT NULL DEFAULT 0,
  interest DECIMAL(14,2) NOT NULL DEFAULT 0,
  late_fee DECIMAL(14,2) NOT NULL DEFAULT 0,
  total_liability DECIMAL(14,2) NOT NULL DEFAULT 0,
  payment_required TINYINT(1) NOT NULL DEFAULT 0,
  payment_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  payment_date DATE DEFAULT NULL,
  challan_cin VARCHAR(120) DEFAULT NULL,
  validation_status VARCHAR(30) DEFAULT NULL,
  validation_error_count INT NOT NULL DEFAULT 0,
  validation_message TEXT,
  arn VARCHAR(60) DEFAULT NULL,
  filing_date DATE DEFAULT NULL,
  document_link VARCHAR(255) DEFAULT NULL,
  remarks TEXT,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gst_filing_id (gst_filing_id),
  KEY idx_gst_due (due_date),
  KEY idx_gst_fy (financial_year),
  KEY idx_gst_gstin (gstin),
  KEY idx_gst_status (filing_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 10. TDS Filings  (TDS-#### id)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tds_filings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tds_filing_id VARCHAR(40) NOT NULL,
  financial_year VARCHAR(12) DEFAULT NULL,
  quarter VARCHAR(20) DEFAULT NULL,
  month VARCHAR(20) DEFAULT NULL,
  tan VARCHAR(15) DEFAULT NULL,
  invoice_id VARCHAR(40) DEFAULT NULL,
  deductee_id VARCHAR(40) DEFAULT NULL,
  deductee_name VARCHAR(190) DEFAULT NULL,
  pan VARCHAR(15) DEFAULT NULL,
  section VARCHAR(20) DEFAULT NULL,
  payment_type VARCHAR(40) DEFAULT NULL,
  gross_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  tds_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
  tds_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  interest DECIMAL(14,2) NOT NULL DEFAULT 0,
  late_fee DECIMAL(14,2) NOT NULL DEFAULT 0,
  total_liability DECIMAL(14,2) NOT NULL DEFAULT 0,
  tds_paid DECIMAL(14,2) NOT NULL DEFAULT 0,
  balance_payable_refund DECIMAL(14,2) NOT NULL DEFAULT 0,
  challan_no VARCHAR(80) DEFAULT NULL,
  challan_date DATE DEFAULT NULL,
  payment_reference VARCHAR(120) DEFAULT NULL,
  return_type VARCHAR(40) DEFAULT NULL,
  filing_due_date DATE DEFAULT NULL,
  filing_date DATE DEFAULT NULL,
  acknowledgement_no VARCHAR(80) DEFAULT NULL,
  return_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  correction_required TINYINT(1) NOT NULL DEFAULT 0,
  correction_date DATE DEFAULT NULL,
  remarks TEXT,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_tds_filing_id (tds_filing_id),
  KEY idx_tds_due (filing_due_date),
  KEY idx_tds_fy (financial_year),
  KEY idx_tds_deductee (deductee_name),
  KEY idx_tds_status (return_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Seed automatic record-id prefixes used by these modules (idempotent).
-- Purchase Bills use a manually entered PO Number, so no prefix is seeded.
-- ---------------------------------------------------------------------------
INSERT INTO record_id_sequences (prefix, next_number) VALUES
  ('EXP', 0), ('FTE', 0), ('FRL', 0), ('BTX', 0),
  ('ACC', 0), ('COA', 0), ('CV', 0), ('GST', 0), ('TDS', 0)
ON DUPLICATE KEY UPDATE prefix = VALUES(prefix);
