CREATE TABLE IF NOT EXISTS hr_departments (department_id VARCHAR(40) PRIMARY KEY, department_name VARCHAR(150) NOT NULL, parent_department_id VARCHAR(40), head_employee_id VARCHAR(40), description TEXT, status VARCHAR(30) NOT NULL DEFAULT 'Active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hr_designations (designation_id VARCHAR(40) PRIMARY KEY, designation_name VARCHAR(150) NOT NULL, parent_designation_id VARCHAR(40), level_name VARCHAR(80), description TEXT, status VARCHAR(30) NOT NULL DEFAULT 'Active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hr_promotions (promotion_id BIGINT AUTO_INCREMENT PRIMARY KEY, employee_id BIGINT NOT NULL, effective_date DATE NOT NULL, old_designation_id VARCHAR(40), new_designation_id VARCHAR(40), old_department_id VARCHAR(40), new_department_id VARCHAR(40), old_grade VARCHAR(80), new_grade VARCHAR(80), old_salary DECIMAL(14,2), new_salary DECIMAL(14,2), reason TEXT, approved_by BIGINT, approver_name VARCHAR(150), status VARCHAR(30) DEFAULT 'Pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hr_awards (award_id BIGINT AUTO_INCREMENT PRIMARY KEY, employee_id BIGINT NOT NULL, award_name VARCHAR(180) NOT NULL, award_date DATE NOT NULL, given_by VARCHAR(150), description TEXT, badge_url VARCHAR(500), status VARCHAR(30) DEFAULT 'Active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hr_appreciations (appreciation_id BIGINT AUTO_INCREMENT PRIMARY KEY, employee_id BIGINT NOT NULL, title VARCHAR(180) NOT NULL, message TEXT NOT NULL, given_by VARCHAR(150), appreciation_date DATE NOT NULL, category VARCHAR(80), status VARCHAR(30) DEFAULT 'Active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hr_passport_visa (record_id BIGINT AUTO_INCREMENT PRIMARY KEY, employee_id BIGINT NOT NULL, passport_number VARCHAR(80), passport_issue_date DATE, passport_expiry_date DATE, visa_type VARCHAR(80), visa_number VARCHAR(80), visa_issue_date DATE, visa_expiry_date DATE, country VARCHAR(100), status VARCHAR(30) DEFAULT 'Active', passport_path VARCHAR(500), visa_path VARCHAR(500), remarks TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hr_holidays (holiday_id BIGINT AUTO_INCREMENT PRIMARY KEY, holiday_name VARCHAR(180) NOT NULL, holiday_date DATE NOT NULL, holiday_type VARCHAR(80), applicable_department_id VARCHAR(40), applicable_state_ut VARCHAR(100), optional TINYINT(1) DEFAULT 0, description TEXT, status VARCHAR(30) DEFAULT 'Active', year INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT IGNORE INTO modules (name, slug, description, icon, sort_order) SELECT 'HR', 'hr', 'People operations', 'users', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM modules WHERE slug='hr');
INSERT IGNORE INTO features (module_id,name,slug,sort_order) SELECT id,'HR Master Data','hr.view_master_data',30 FROM modules WHERE slug='hr';
