CREATE TABLE IF NOT EXISTS admin_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(120) NOT NULL UNIQUE,
  category VARCHAR(80) NOT NULL,
  label VARCHAR(160) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  value TEXT DEFAULT NULL,
  value_type ENUM('text','number','boolean','select','url') NOT NULL DEFAULT 'text',
  is_secret BOOLEAN NOT NULL DEFAULT FALSE,
  updated_by BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_admin_settings_category (category)
);
