"use client"

import useSWR from "swr"
import { fetcher } from "@/lib/fetcher"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { ContractStatusBadge } from "@/components/legal/contract-status-badge"
import { sourceMeta, type GeneratedContract } from "@/lib/legal-contracts-shared"
import { Download, ExternalLink, Loader2 } from "lucide-react"

function sanitizeHtml(html: string): string {
  return html
    .replace(/<\s*(script|style)[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi, "")
    .replace(/\son\w+\s*=\s*"[^"]*"/gi, "")
    .replace(/\son\w+\s*=\s*'[^']*'/gi, "")
    .replace(/javascript:/gi, "")
}

function fmtDate(d: string | null | undefined) {
  if (!d) return "—"
  const dt = new Date(d)
  return isNaN(dt.getTime()) ? "—" : dt.toLocaleDateString(undefined, { day: "2-digit", month: "short", year: "numeric" })
}

function Field({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</span>
      <span className="text-sm text-foreground">{value ?? "—"}</span>
    </div>
  )
}

export function ContractDetailDialog({ contractId, onClose }: { contractId: number; onClose: () => void }) {
  const { data, isLoading } = useSWR<{ contract: GeneratedContract }>(`/api/legal/contracts/${contractId}`, fetcher)
  const c = data?.contract

  return (
    <Dialog open onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-h-[94vh] w-[calc(100vw-1.5rem)] overflow-y-auto sm:max-w-5xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-3">
            {c?.title || "Contract"}
            {c && <ContractStatusBadge status={c.status} />}
          </DialogTitle>
          <DialogDescription>
            {c ? `${c.contract_uid}${c.reference_no ? ` · ${c.reference_no}` : ""}` : "Loading contract…"}
          </DialogDescription>
        </DialogHeader>

        {isLoading || !c ? (
          <div className="flex items-center gap-2 py-16 text-muted-foreground"><Loader2 className="size-4 animate-spin" /> Loading…</div>
        ) : (
          <div className="grid gap-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.3fr)]">
            <div className="flex flex-col gap-4">
              <div className="grid grid-cols-2 gap-4 rounded-lg border bg-card p-4">
                <Field label="Type" value={c.contract_type} />
                <Field label="Category" value={c.category} />
                <Field label="Source" value={sourceMeta(c.source).label.replace(/ \(.*\)/, "")} />
                <Field label="Counterparty" value={c.party_name} />
                <Field label="Version" value={`v${c.version}`} />
                <Field label="From template" value={c.template_name} />
              </div>
              <div className="grid grid-cols-2 gap-4 rounded-lg border bg-card p-4">
                <Field label="Effective" value={fmtDate(c.effective_date)} />
                <Field label="Start" value={fmtDate(c.start_date)} />
                <Field label="End" value={fmtDate(c.end_date)} />
                <Field label="Renewal" value={fmtDate(c.renewal_date)} />
              </div>
              <div className="rounded-lg border bg-card p-4">
                <Field label="Generated by" value={`${c.generated_by_name || "—"} · ${fmtDate(c.created_at)}`} />
              </div>
              <div className="flex flex-wrap gap-2">
                <Button asChild>
                  <a href={`/api/legal/contracts/${c.id}/pdf?download=1`}>
                    <Download data-icon="inline-start" /> Download PDF
                  </a>
                </Button>
                <Button variant="outline" asChild>
                  <a href={`/api/legal/contracts/${c.id}/pdf`} target="_blank" rel="noreferrer">
                    <ExternalLink data-icon="inline-start" /> Open PDF
                  </a>
                </Button>
              </div>
            </div>

            <div className="max-h-[70vh] overflow-y-auto rounded-lg border bg-white p-6 text-sm leading-relaxed text-slate-900 shadow-sm">
              <div
                className="[&_h1]:mb-2 [&_h1]:text-lg [&_h1]:font-semibold [&_h2]:mb-1.5 [&_h2]:mt-3 [&_h2]:font-semibold [&_p]:mb-2 [&_ul]:mb-2 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:mb-2 [&_ol]:list-decimal [&_ol]:pl-6 [&_table]:w-full [&_td]:border [&_td]:border-slate-300 [&_td]:p-1.5"
                dangerouslySetInnerHTML={{ __html: sanitizeHtml(c.content) }}
              />
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}
