"use client"
import { useEffect, useMemo, useState } from "react"
import { Search, Save, Settings2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

type Setting={setting_key:string;category:string;label:string;description?:string;value:string;value_type:string;is_secret:boolean}
const requested=["Company Settings","Business Address","Downloads","App Settings","Profile Settings","Notification Settings","Currency Settings","Payment Credentials","Finance Settings","Contract Settings","Tax Settings","Ticket Settings","Project Settings","Attendance Settings","Leaves Settings","Custom Fields","Roles & Permissions","Message Settings","Lead Settings","Time Log Settings","Task Settings","Security Settings","Theme Settings","Module Settings","Storage Settings","Language Settings","Social Login Settings","Google Calendar Settings","Custom Link Settings","GDPR Settings","Database Backup Settings","Sign Up Settings","Asset Settings","Payroll Settings","Overtime Settings","Performance Settings","Purchase Settings","Recruit","Rest API Setting","Update App"]
export function SettingsHub(){const [items,setItems]=useState<Setting[]>([]);const [search,setSearch]=useState("");const [active,setActive]=useState("All Settings");const [message,setMessage]=useState("");useEffect(()=>{fetch("/api/admin/settings").then(r=>r.json()).then(setItems)},[]);const visible=useMemo(()=>items.filter(i=>(active==="All Settings"||i.category===active)&&`${i.label} ${i.category}`.toLowerCase().includes(search.toLowerCase())),[items,active,search]);const categories=["All Settings",...requested];async function save(i:Setting){await fetch("/api/admin/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({setting_key:i.setting_key,value:i.value})});setMessage(`${i.label} saved`);setTimeout(()=>setMessage(""),1800)}return <div className="grid gap-6 lg:grid-cols-[250px_1fr]"><Card className="h-fit"><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 className="size-5 text-primary"/>Settings</CardTitle><CardDescription>Admin-only workspace configuration.</CardDescription></CardHeader><CardContent className="flex flex-col gap-1">{categories.map(c=><button key={c} onClick={()=>setActive(c)} className={`rounded-md px-3 py-2 text-left text-sm ${active===c?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-muted"}`}>{c}</button>)}</CardContent></Card><div className="flex flex-col gap-5"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search settings..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{message&&<p className="self-center text-sm text-emerald-400">{message}</p>}</div><div className="grid gap-4 md:grid-cols-2">{visible.map(i=><Card key={i.setting_key}><CardHeader><CardTitle className="text-base">{i.label}</CardTitle><CardDescription>{i.description||i.category}</CardDescription></CardHeader><CardContent className="flex gap-2"><div className="flex-1"><Label className="sr-only" htmlFor={i.setting_key}>{i.label}</Label>{i.value_type==="boolean"?<select id={i.setting_key} className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={i.value} onChange={e=>setItems(items.map(x=>x.setting_key===i.setting_key?{...x,value:e.target.value}:x))}><option value="true">Enabled</option><option value="false">Disabled</option></select>:<Input id={i.setting_key} type={i.is_secret?"password":i.value_type==="number"?"number":"text"} value={i.value} onChange={e=>setItems(items.map(x=>x.setting_key===i.setting_key?{...x,value:e.target.value}:x))}/>}</div><Button className="mt-6" size="icon" onClick={()=>save(i)} aria-label={`Save ${i.label}`}><Save className="size-4"/></Button></CardContent></Card>)}</div></div></div>}
