"use client"
import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { MessageSquare, Plus, Send, Users } from "lucide-react"

type Conversation = { id:number; subject:string|null; last_message:string|null; last_sender:string|null; unread:number }
type User = { id:number; name:string; email:string; role:string }
export function MessagesClient() {
 const [items,setItems]=useState<Conversation[]>([]); const [users,setUsers]=useState<User[]>([]); const [selected,setSelected]=useState<number|null>(null); const [messages,setMessages]=useState<any[]>([]); const [body,setBody]=useState(""); const [recipientId,setRecipientId]=useState(""); const [subject,setSubject]=useState(""); const [compose,setCompose]=useState(false); const [error,setError]=useState("")
 async function load(){ const [a,b]=await Promise.all([fetch("/api/messages"),fetch("/api/messages/recipients")]); if(a.ok)setItems((await a.json()).conversations); if(b.ok)setUsers((await b.json()).users) }
 useEffect(()=>{load()},[])
 async function open(id:number){setSelected(id); const r=await fetch(`/api/messages/${id}`); if(r.ok)setMessages((await r.json()).messages); load()}
 async function send(){setError(""); if(!body.trim())return; const url=compose?"/api/messages":`/api/messages/${selected}`; const payload=compose?{recipientId,subject,body}:{body}; const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); if(!r.ok){setError((await r.json()).error||"Unable to send");return} setBody("");setSubject("");setRecipientId("");setCompose(false);await load()}
 return <main className="erp-page"><header className="erp-pagehead"><div><h1>Messages</h1><span>Home • Messages</span></div><div className="erp-utilities"><MessageSquare/><Users/><Plus/></div></header><div className="p-6 md:p-8"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-2xl font-semibold">Employee communication</h2><p className="text-sm text-muted-foreground">Message teammates, admins, and management securely.</p></div><Button onClick={()=>setCompose(true)}><Plus className="mr-2 size-4"/>New message</Button></div><div className="grid min-h-[520px] gap-5 lg:grid-cols-[320px_1fr]"><Card><CardHeader><CardTitle className="text-base">Inbox</CardTitle></CardHeader><CardContent className="flex flex-col gap-2">{items.length?items.map(c=><button key={c.id} onClick={()=>open(c.id)} className={`rounded-lg p-3 text-left hover:bg-muted ${selected===c.id?"bg-primary/10":""}`}><div className="flex justify-between gap-2 font-medium"><span>{c.subject||"Conversation"}</span>{Number(c.unread)>0&&<span className="rounded-full bg-primary px-2 text-xs text-primary-foreground">{c.unread}</span>}</div><p className="mt-1 truncate text-xs text-muted-foreground">{c.last_sender}: {c.last_message}</p></button>):<div className="py-12 text-center text-sm text-muted-foreground">No conversations yet.</div>}</CardContent></Card><Card className="flex flex-col"><CardHeader><CardTitle className="text-base">{compose?"New message":selected?"Conversation":"Select a conversation"}</CardTitle></CardHeader><CardContent className="flex flex-1 flex-col gap-4">{compose?<><label className="grid gap-2 text-sm font-medium">Recipient<select className="h-10 rounded-md border bg-background px-3" value={recipientId} onChange={e=>setRecipientId(e.target.value)}><option value="">Select employee, admin, or management</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</select></label><Input placeholder="Subject (optional)" value={subject} onChange={e=>setSubject(e.target.value)}/></>:selected? <div className="flex flex-1 flex-col gap-3 overflow-y-auto">{messages.map(m=><div key={m.id} className="rounded-lg bg-muted p-3"><div className="mb-1 text-xs font-semibold">{m.sender_name}</div><p className="whitespace-pre-wrap text-sm">{m.body}</p></div>)}</div>:<div className="flex flex-1 flex-col items-center justify-center text-center text-muted-foreground"><MessageSquare className="mb-3 size-9"/><p>Select a conversation or start a new message.</p></div>} {(compose||selected)&&<div className="mt-auto flex gap-2 border-t pt-4"><Input placeholder="Write a message..." value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><Button onClick={send} aria-label="Send message"><Send className="size-4"/></Button></div>}{error&&<p className="text-sm text-destructive">{error}</p>}</CardContent></Card></div></div></main>
}
