"use client"
import { useState } from "react"
import useSWR from "swr"
import { fetcher } from "@/lib/fetcher"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Plus, Search, Users2 } from "lucide-react"

const fields = [
  ["employee_id","Employee ID"],["employee_name","Employee Name"],["gender","Gender"],["dob","DOB"],["personal_email","Personal Email"],["official_email","Official Email"],["mobile","Mobile"],["alternate_mobile","Alternate Mobile"],["address","Address"],["city","City"],["state","State"],["country","Country"],["postal_code","Postal Code"],["emergency_contact_name","Emergency Contact Name"],["emergency_contact_phone","Emergency Contact Phone"],["emergency_contact_relation","Emergency Contact Relation"],["relative_name","Relative Name"],["relative_relationship","Relationship"],["relative_primary_phone","Primary Phone"],["relative_alternate_phone","Alternate Phone"],["relative_email","Email"],["relative_address","Address"],["department","Department"],["designation","Designation"],["reporting_manager","Reporting Manager"],["employment_type","Employment Type"],["joining_date","Joining Date"],["probation_end_date","Probation End Date"],["confirmation_date","Confirmation Date"],["employment_status","Employment Status"],["onboarding_status","Onboarding Status"],["work_location","Work Location"],["work_mode","Work Mode"],["shift","Shift"],["employee_grade","Employee Grade"],["document_status","Document Status"],["agreement_status","Agreement Status"],["consent_status","Consent Status"],["compliance_status","Compliance Status"],["it_access_status","IT Access Status"],["asset_status","Asset Status"],["training_status","Training Status"],["performance_status","Performance Status"],["notice_period","Notice Period"],["notice_period_status","Notice Period Status"],["exit_status","Exit Status"],["exit_date","Exit Date"],["exit_reason","Exit Reason"],["skills","Skills"],["notes","Notes"]] as const

function EmployeeDialog({ onSaved }: { onSaved: () => void }) { const [open,setOpen]=useState(false); const [form,setForm]=useState<Record<string,string>>({}); const [saving,setSaving]=useState(false); async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const r=await fetch("/api/hr/employees",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setSaving(false);if(r.ok){setOpen(false);setForm({});onSaved()}} return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger><Plus /> Add employee</DialogTrigger><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>Add employee</DialogTitle></DialogHeader><form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label])=><div key={key} className="grid gap-2"><Label htmlFor={key}>{label}{key==="employee_id"||key==="employee_name"?" *":""}</Label><Input id={key} type={key.includes("date")||key==="dob"?"date":"text"} required={key==="employee_id"||key==="employee_name"} value={form[key]||""} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>)}<Button type="submit" disabled={saving} className="sm:col-span-2">{saving?"Saving…":"Save employee"}</Button></form></DialogContent></Dialog> }
export function EmployeesClient(){const {data,mutate}=useSWR<{employees:any[]}>("/api/hr/employees",fetcher);const [search,setSearch]=useState("");const employees=(data?.employees||[]).filter(e=>`${e.employee_id} ${e.employee_name} ${e.department} ${e.designation} ${e.official_email}`.toLowerCase().includes(search.toLowerCase()));return <div className="flex flex-col gap-6 p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-3"><Users2 className="size-7 text-primary"/><h1 className="text-2xl font-semibold tracking-tight">Employees</h1></div><p className="mt-1 text-sm text-muted-foreground">Complete employee master records and workforce details.</p></div><EmployeeDialog onSaved={()=>mutate()}/></div><div className="flex items-center gap-3"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search employees..." value={search} onChange={e=>setSearch(e.target.value)}/></div><Badge variant="secondary">{employees.length} employees</Badge></div><div className="overflow-x-auto rounded-md border bg-card"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-muted-foreground">{["Employee","Contact","Department","Employment","Work","Status"].map(x=><th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{employees.map(e=><tr key={e.id} className="border-b last:border-0"><td className="px-4 py-4"><div className="font-medium">{e.employee_name}</div><div className="text-xs text-muted-foreground">{e.employee_id} · {e.designation||"No designation"}</div></td><td className="px-4 py-4"><div>{e.official_email||e.personal_email||"—"}</div><div className="text-xs text-muted-foreground">{e.mobile||"No mobile"}</div></td><td className="px-4 py-4">{e.department||"—"}<div className="text-xs text-muted-foreground">Manager: {e.reporting_manager||"—"}</div></td><td className="px-4 py-4">{e.employment_type||"—"}<div className="text-xs text-muted-foreground">Joined: {e.joining_date||"—"}</div></td><td className="px-4 py-4">{e.work_mode||"—"}<div className="text-xs text-muted-foreground">{e.work_location||"—"}</div></td><td className="px-4 py-4"><Badge>{e.employment_status||"Active"}</Badge></td></tr>)}{employees.length===0&&<tr><td colSpan={6} className="px-4 py-12 text-center text-muted-foreground">No employees found.</td></tr>}</tbody></table></div></div>}
