"use client"
import { useState } from "react"
import useSWR from "swr"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { fetcher } from "@/lib/fetcher"

const statuses = ["Pending", "Manager Approved", "Manager Rejected", "HR Approved", "HR Rejected", "Cancelled"]
export function LeaveRequestsClient() {
  const { data, mutate } = useSWR<{ requests: any[] }>("/api/hr/leave-requests", fetcher)
  const { data: employees } = useSWR<{ employees: any[] }>("/api/hr/employees", fetcher)
  const [status, setStatus] = useState("all")
  const [form, setForm] = useState({ employee_id: "", employee_name: "", leave_type_id: "", from_date: "", to_date: "", reason: "", remarks: "" })
  const requests = (data?.requests || []).filter((r) => status === "all" || r.status === status)
  async function submit(e: React.FormEvent) { e.preventDefault(); const employee = employees?.employees.find((x) => String(x.id) === form.employee_id); await fetch("/api/hr/leave-requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, employee_name: employee?.employee_name || "" }) }); setForm({ employee_id: "", employee_name: "", leave_type_id: "", from_date: "", to_date: "", reason: "", remarks: "" }); mutate() }
  async function update(id: number, nextStatus: string) { await fetch("/api/hr/leave-requests", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status: nextStatus }) }); mutate() }
  return <main className="space-y-6 p-6"><header><p className="text-sm text-muted-foreground">Human Resources</p><h1 className="text-3xl font-semibold">Leave Requests</h1><p className="text-muted-foreground">Submit, review, and track employee leave.</p></header><form onSubmit={submit} className="grid gap-3 rounded-xl border bg-card p-4 md:grid-cols-4"><Select value={form.employee_id} onValueChange={(v) => setForm({ ...form, employee_id: v })}><SelectTrigger><SelectValue placeholder="Employee" /></SelectTrigger><SelectContent>{(employees?.employees || []).map((e) => <SelectItem key={e.id} value={String(e.id)}>{e.employee_name}</SelectItem>)}</SelectContent></Select><Input placeholder="Leave Type ID" value={form.leave_type_id} onChange={(e) => setForm({ ...form, leave_type_id: e.target.value })} required /><Input type="date" value={form.from_date} onChange={(e) => setForm({ ...form, from_date: e.target.value })} required /><Input type="date" value={form.to_date} onChange={(e) => setForm({ ...form, to_date: e.target.value })} required /><Textarea className="md:col-span-3" placeholder="Reason" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} required /><Button type="submit">Submit request</Button></form><div className="flex gap-2"><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-56"><SelectValue placeholder="Filter status" /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{statuses.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><section className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Request</th><th className="p-3">Employee</th><th className="p-3">Leave</th><th className="p-3">Dates</th><th className="p-3">Days</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{requests.map((r) => <tr key={r.id} className="border-b"><td className="p-3 font-medium">{r.request_id}</td><td className="p-3">{r.employee_name}</td><td className="p-3">{r.leave_type_id}</td><td className="p-3">{r.from_date} → {r.to_date}</td><td className="p-3">{r.days}</td><td className="p-3">{r.status}</td><td className="flex gap-2 p-3">{r.status === "Pending" && <><Button size="sm" variant="outline" onClick={() => update(r.id, "Manager Approved")}>Approve</Button><Button size="sm" variant="destructive" onClick={() => update(r.id, "Manager Rejected")}>Reject</Button></>}</td></tr>)}</tbody></table></section></main>
}
