"use client"
import { useState } from "react"
import useSWR from "swr"
import { fetcher } from "@/lib/fetcher"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"

const fields = [["attendance_id","Attendance ID"],["employee_id","Employee ID"],["employee_name","Employee Name"],["work_date","Work Date"],["clock_in","Clock In"],["clock_out","Clock Out"],["break_minutes","Break Minutes"],["status","Status"],["late_minutes","Late Minutes"],["early_leaving_minutes","Early Leaving Minutes"],["overtime_hours","Overtime Hours"],["location","Location"],["latitude","Latitude"],["longitude","Longitude"],["source","Source"],["remarks","Remarks"]]
export function AttendanceClient() {
  const { data, mutate } = useSWR<{ attendance: any[] }>("/api/hr/attendance", fetcher); const [open, setOpen] = useState(false); const [form, setForm] = useState<Record<string, string>>({ work_date: new Date().toISOString().slice(0,10), status: "Present", source: "Manual" }); const rows = data?.attendance ?? []
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event: React.FormEvent) { event.preventDefault(); await fetch("/api/hr/attendance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setOpen(false); setForm({ work_date: new Date().toISOString().slice(0,10), status: "Present", source: "Manual" }); mutate() }
  return <main className="space-y-6 p-6"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Attendance</h1><p className="text-sm text-muted-foreground">Daily attendance, work hours and regularisation tracking.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger>Add attendance</DialogTrigger><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Add attendance record</DialogTitle></DialogHeader><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label]) => <div key={key} className={key === "remarks" ? "sm:col-span-2" : ""}><Label htmlFor={key}>{label}</Label>{key === "remarks" ? <Textarea id={key} value={form[key] || ""} onChange={(e) => update(key,e.target.value)} /> : <Input id={key} type={key.includes("date") ? "date" : key.includes("clock") ? "datetime-local" : key.includes("minutes") || key.includes("hours") || key === "latitude" || key === "longitude" ? "number" : "text"} value={form[key] || ""} onChange={(e) => update(key,e.target.value)} required={["attendance_id","employee_id","employee_name","work_date"].includes(key)} />}</div>)}<Button type="submit" className="sm:col-span-2">Save attendance</Button></form></DialogContent></Dialog></header><div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead><tr className="border-b bg-muted/30 text-left"><th className="p-3">Attendance ID</th><th className="p-3">Employee</th><th className="p-3">Work Date</th><th className="p-3">In / Out</th><th className="p-3">Hours</th><th className="p-3">Status</th><th className="p-3">Source</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.id} className="border-b"><td className="p-3">{row.attendance_id}</td><td className="p-3">{row.employee_name}<div className="text-xs text-muted-foreground">#{row.employee_id}</div></td><td className="p-3">{row.work_date}</td><td className="p-3">{row.clock_in || "—"} / {row.clock_out || "—"}</td><td className="p-3">{row.working_hours}</td><td className="p-3">{row.status}</td><td className="p-3">{row.source}</td></tr>)}</tbody></table></div></main>
}
