"use client"
import { useState } from "react"
import useSWR from "swr"
import { fetcher } from "@/lib/fetcher"

type Employee = { id:number; employee_name:string }
type RequestRow = { id:number; request_id:string; employee_name:string; work_date:string; requested_clock_in:string|null; requested_clock_out:string|null; reason:string; status:string; attachment_path:string|null; requested_at:string; reviewed_by:string|null }
export function AttendanceRegularisationClient() {
  const { data: employeeData } = useSWR<{employees:Employee[]}>("/api/hr/employees", fetcher)
  const { data, mutate } = useSWR<{requests:RequestRow[]}>("/api/hr/attendance-regularisation", fetcher)
  const [message, setMessage] = useState("")
  const [form, setForm] = useState({ employee_id:"", work_date:"", requested_clock_in:"", requested_clock_out:"", reason:"", attachment_path:"" })
  const employees = employeeData?.employees ?? []
  async function upload(file: File) { const fd = new FormData(); fd.append("file", file); const r = await fetch("/api/hr/attendance-regularisation/upload", { method:"POST", body:fd }); const json=await r.json(); if(!r.ok) throw new Error(json.error); setForm((f)=>({...f,attachment_path:json.pathname})); setMessage("Attachment uploaded") }
  async function submit(e: React.FormEvent) { e.preventDefault(); const r=await fetch("/api/hr/attendance-regularisation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const json=await r.json(); setMessage(r.ok ? `Request ${json.requestId} created` : json.error); if(r.ok){setForm({employee_id:"",work_date:"",requested_clock_in:"",requested_clock_out:"",reason:"",attachment_path:""});mutate()} }
  async function review(id:number,status:string){await fetch("/api/hr/attendance-regularisation",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});mutate()}
  return <main className="space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Attendance Regularisation</h1><p className="text-muted-foreground">Submit and review attendance correction requests.</p></div><form onSubmit={submit} className="grid gap-3 rounded-xl border bg-card p-4 md:grid-cols-3"><select required value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})} className="rounded-md border bg-background p-2"><option value="">Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_name}</option>)}</select><input required type="date" value={form.work_date} onChange={e=>setForm({...form,work_date:e.target.value})} className="rounded-md border bg-background p-2"/><input type="datetime-local" value={form.requested_clock_in} onChange={e=>setForm({...form,requested_clock_in:e.target.value})} className="rounded-md border bg-background p-2"/><input type="datetime-local" value={form.requested_clock_out} onChange={e=>setForm({...form,requested_clock_out:e.target.value})} className="rounded-md border bg-background p-2"/><input required placeholder="Reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} className="rounded-md border bg-background p-2 md:col-span-2"/><input type="file" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])} className="text-sm"/><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground">Submit request</button>{message&&<p className="text-sm text-muted-foreground">{message}</p>}</form><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Request ID</th><th className="p-3">Employee</th><th className="p-3">Work Date</th><th className="p-3">Requested Time</th><th className="p-3">Reason</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{(data?.requests??[]).map(row=><tr key={row.id} className="border-b"><td className="p-3">{row.request_id}</td><td className="p-3">{row.employee_name}</td><td className="p-3">{row.work_date}</td><td className="p-3">{row.requested_clock_in||"—"} → {row.requested_clock_out||"—"}</td><td className="max-w-xs p-3">{row.reason}</td><td className="p-3">{row.status}</td><td className="p-3">{row.status==="Pending"&&<span className="flex gap-2"><button onClick={()=>review(row.id,"Approved")} className="text-primary">Approve</button><button onClick={()=>review(row.id,"Rejected")} className="text-destructive">Reject</button></span>}</td></tr>)}</tbody></table></div></main>
}
