"use client"
import { useState } from "react"
import useSWR from "swr"
import { fetcher } from "@/lib/fetcher"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { FileCheck2, Upload } from "lucide-react"

const documentTypes = ["Profile Photo","PAN","Aadhar","Bank PassBook/Cancel Cheque","Highest Qualification Degree","Experience Certificate 1","Experience Certificate 2","Experience Certificate 3","Certificate (If Any)","Other Document"]
export function EmployeeDocumentsClient() {
  const { data: employeeData } = useSWR<{ employees: any[] }>("/api/hr/employees", fetcher)
  const { data, mutate } = useSWR<{ documents: any[] }>("/api/hr/employee-documents", fetcher)
  const [employeeId, setEmployeeId] = useState(""); const [type, setType] = useState(""); const [file, setFile] = useState<File | null>(null); const [remarks, setRemarks] = useState(""); const [saving, setSaving] = useState(false)
  async function upload(e: React.FormEvent) { e.preventDefault(); if (!employeeId || !type) return; setSaving(true); const fd = new FormData(); fd.set("employee_id", employeeId); fd.set("document_type", type); fd.set("remarks", remarks); if (file) fd.set("file", file); const res = await fetch("/api/hr/employee-documents", { method: "POST", body: fd }); setSaving(false); if (res.ok) { setEmployeeId(""); setType(""); setFile(null); setRemarks(""); mutate() } }
  return <div className="flex flex-col gap-6 p-6 md:p-8"><div><div className="flex items-center gap-3"><FileCheck2 className="size-7 text-primary"/><h1 className="text-2xl font-semibold">Employee Documents</h1></div><p className="mt-1 text-sm text-muted-foreground">Securely upload, track, and review employee documents.</p></div><form onSubmit={upload} className="grid gap-4 rounded-lg border bg-card p-5 md:grid-cols-4"><div className="grid gap-2"><Label>Employee</Label><Select value={employeeId} onValueChange={(value) => setEmployeeId(value || "")}><SelectTrigger><SelectValue placeholder="Select employee" /></SelectTrigger><SelectContent>{(employeeData?.employees || []).map(e => <SelectItem key={e.id} value={String(e.id)}>{e.employee_id} · {e.employee_name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Document type</Label><Select value={type} onValueChange={(value) => setType(value || "")}><SelectTrigger><SelectValue placeholder="Select document" /></SelectTrigger><SelectContent>{documentTypes.map(x => <SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>File</Label><Input type="file" onChange={e => setFile(e.target.files?.[0] || null)} /></div><div className="grid gap-2"><Label>Remarks</Label><Input value={remarks} onChange={e => setRemarks(e.target.value)} placeholder="Optional remarks" /></div><Button type="submit" disabled={saving || !employeeId || !type} className="md:col-span-4"><Upload data-icon="inline-start" />{saving ? "Uploading…" : "Upload document"}</Button></form><div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-left text-muted-foreground">{["Employee","Document","File","Verification","Status","Remarks"].map(x => <th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{(data?.documents || []).map(d => <tr key={d.id} className="border-b last:border-0"><td className="px-4 py-3"><div className="font-medium">{d.employee_name}</div><div className="text-xs text-muted-foreground">{d.employee_code}</div></td><td className="px-4 py-3">{d.document_type}</td><td className="px-4 py-3">{d.file_path ? <a className="text-primary underline" href={`/api/hr/employee-documents/file?pathname=${encodeURIComponent(d.file_path)}`} target="_blank">{d.file_name}</a> : "No file"}</td><td className="px-4 py-3">{d.verified ? `Verified${d.verifier_name ? ` by ${d.verifier_name}` : ""}` : "Pending"}</td><td className="px-4 py-3"><Badge variant={d.status === "Approved" ? "default" : "secondary"}>{d.status}</Badge></td><td className="px-4 py-3 text-muted-foreground">{d.remarks || "—"}</td></tr>)}</tbody></table></div></div>
}
