"use client"
import { useState } from "react"
import useSWR from "swr"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { fetcher } from "@/lib/fetcher"

export function ShiftsClient() {
  const { data, mutate } = useSWR<{ shifts: any[] }>("/api/hr/shifts", fetcher)
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(""); const [form, setForm] = useState({ shift_id:"", shift_name:"", start_time:"09:00", end_time:"18:00", break_minutes:"60", overtime_enabled:false, status:"Active", description:"" })
  const shifts = (data?.shifts || []).filter((s) => `${s.shift_id} ${s.shift_name}`.toLowerCase().includes(search.toLowerCase()))
  async function submit(e: React.FormEvent) { e.preventDefault(); await fetch("/api/hr/shifts", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(form) }); setOpen(false); setForm({ shift_id:"", shift_name:"", start_time:"09:00", end_time:"18:00", break_minutes:"60", overtime_enabled:false, status:"Active", description:"" }); mutate() }
  return <main className="space-y-6"><header><p className="text-sm text-muted-foreground">HR / Workforce</p><h1 className="text-3xl font-semibold tracking-tight">Shifts</h1><p className="text-muted-foreground">Manage working schedules, breaks, and overtime settings.</p></header><div className="flex gap-3"><Input placeholder="Search shifts..." value={search} onChange={(e)=>setSearch(e.target.value)} /><Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button />}>Add shift</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add shift</DialogTitle></DialogHeader><form onSubmit={submit} className="grid gap-4"><div className="grid grid-cols-2 gap-3">{[["shift_id","Shift ID"],["shift_name","Shift Name"],["start_time","Start Time"],["end_time","End Time"],["break_minutes","Break Minutes"]].map(([key,label])=><div className="grid gap-2" key={key}><Label htmlFor={key}>{label}</Label><Input id={key} type={key.includes("time")?"time":key==="break_minutes"?"number":"text"} required={key!=="break_minutes"} value={(form as any)[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></div>)}</div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.overtime_enabled} onChange={(e)=>setForm({...form,overtime_enabled:e.target.checked})}/> Overtime enabled</label><Button type="submit">Save shift</Button></form></DialogContent></Dialog></div><Card><CardHeader><CardTitle>{shifts.length} shifts</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Shift</th><th className="p-3">Timing</th><th className="p-3">Break</th><th className="p-3">Working Hours</th><th className="p-3">Overtime</th><th className="p-3">Status</th></tr></thead><tbody>{shifts.map((s)=><tr key={s.id} className="border-b"><td className="p-3"><b>{s.shift_name}</b><div className="text-xs text-muted-foreground">{s.shift_id}</div></td><td className="p-3">{String(s.start_time).slice(0,5)} – {String(s.end_time).slice(0,5)}</td><td className="p-3">{s.break_minutes} min</td><td className="p-3">{s.working_hours} hrs</td><td className="p-3">{s.overtime_enabled ? "Enabled" : "Disabled"}</td><td className="p-3">{s.status}</td></tr>)}</tbody></table></div></CardContent></Card></main>
}
