"use client"
import { useState } from "react"
import useSWR from "swr"
import { fetcher } from "@/lib/fetcher"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"

const configs:any = {
 requests:{title:"Shift Change Requests",kind:"requests",id:"request_id",fields:[["request_id","Request ID"],["employee_id","Employee ID"],["current_shift_id","Current Shift ID"],["requested_shift_id","Requested Shift ID"],["from_date","From Date"],["to_date","To Date"],["reason","Reason"]]},
 assignments:{title:"Shift Assignments",kind:"assignments",id:"assignment_id",fields:[["assignment_id","Assignment ID"],["employee_id","Employee ID"],["shift_id","Shift ID"],["effective_from","Effective From"],["effective_to","Effective To"],["notes","Notes"]]},
 rotations:{title:"Shift Rotations",kind:"rotations",id:"rotation_id",fields:[["rotation_id","Rotation ID"],["rotation_name","Rotation Name"],["description","Description"],["cycle_type","Cycle Type"],["cycle_length","Cycle Length"],["start_date","Start Date"]]},
 sequences:{title:"Shift Rotation Sequence",kind:"sequences",id:"sequence_id",fields:[["sequence_id","Sequence ID"],["rotation_id","Rotation ID"],["sequence_no","Sequence No"],["shift_id","Shift ID"],["duration_days","Duration Days"]]},
 employees:{title:"Shift Rotation Employees",kind:"employees",id:"record_id",fields:[["record_id","Record ID"],["rotation_id","Rotation ID"],["employee_id","Employee ID"],["start_date","Start Date"],["current_sequence","Current Sequence"],["next_run","Next Run"]]},
}
export function ShiftWorkflowsClient({kind}:{kind:keyof typeof configs}) { const c=configs[kind]; const {data,mutate}=useSWR(`/api/hr/shift-workflows?kind=${kind}`,fetcher); const [open,setOpen]=useState(false); const [search,setSearch]=useState(""); const [form,setForm]=useState<any>({status:"Active",cycle_type:"Weeks"}); const rows=(data?.rows||[]).filter((r:any)=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())); async function submit(e:React.FormEvent){e.preventDefault();await fetch("/api/hr/shift-workflows",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,...form})});setOpen(false);setForm({status:"Active",cycle_type:"Weeks"});mutate()} return <main className="space-y-6"><header><p className="text-sm text-muted-foreground">HR / Workforce</p><h1 className="text-3xl font-semibold tracking-tight">{c.title}</h1><p className="text-muted-foreground">Manage shift planning and workflow records.</p></header><div className="flex gap-3"><Input placeholder={`Search ${c.title.toLowerCase()}...`} value={search} onChange={e=>setSearch(e.target.value)}/><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button>Add record</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add {c.title}</DialogTitle></DialogHeader><form onSubmit={submit} className="grid gap-3">{c.fields.map(([key,label]:string)=><div key={key} className="grid gap-1"><label className="text-sm font-medium" htmlFor={key}>{label}</label><Input id={key} type={key.includes("date")?"date":key.includes("length")||key.includes("no")||key.includes("days")||key.includes("id")?"number":"text"} required={!key.includes("to_date")&&!key.includes("description")&&!key.includes("notes")} value={form[key]||""} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>)}<Button type="submit">Save record</Button></form></DialogContent></Dialog></div><Card><CardHeader><CardTitle>{rows.length} records</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">ID</th><th className="p-3">Employee / Rotation</th><th className="p-3">Status</th><th className="p-3">Created</th></tr></thead><tbody>{rows.map((r:any)=><tr className="border-b" key={r.id}><td className="p-3 font-medium">{r[c.id]}</td><td className="p-3">{r.employee_name||r.employee_id||r.rotation_name||r.rotation_id||"—"}</td><td className="p-3">{r.status||"Pending"}</td><td className="p-3 text-muted-foreground">{r.created_at||r.requested_at||"—"}</td></tr>)}</tbody></table></div></CardContent></Card></main> }
