"use client"

import useSWR from "swr"
import { useMemo, useState } from "react"
import { AlertTriangle, Check, ClipboardCheck, Plus, ShieldAlert, X } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Progress } from "@/components/ui/progress"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

const fetcher = (url: string) => fetch(url).then(async (r) => { const data = await r.json(); if (!r.ok) throw new Error(data.error); return data })
const scopes = ["users", "roles", "permissions", "temporary_access", "api_keys", "service_accounts"] as const
const scopeLabels: Record<string, string> = { users: "Users", roles: "Roles", permissions: "Permissions", temporary_access: "Temporary access", api_keys: "API keys", service_accounts: "Service accounts" }

type Item = { id: number; scope: string; subjectName: string; subjectEmail: string | null; access: string; decision: string; comment: string | null }
type Campaign = { id: number; name: string; reviewerId: number; reviewerName: string | null; startAt: string; dueAt: string; recurrence: string; status: string; escalationLevel: number; items: Item[] }
type User = { id: number; name: string; email: string; role: string }

export function AccessReviewCampaigns() {
  const { data, error, isLoading, mutate } = useSWR<{ campaigns: Campaign[]; users: User[] }>("/api/admin/security/access-reviews", fetcher)
  const [createOpen, setCreateOpen] = useState(false); const [active, setActive] = useState<Campaign | null>(null); const [tab, setTab] = useState("all")
  const [form, setForm] = useState({ name: "", reviewerId: "", startAt: new Date().toISOString().slice(0, 16), dueAt: "", recurrence: "quarterly" })
  const campaigns = data?.campaigns ?? []; const users = data?.users ?? []
  const visible = useMemo(() => tab === "overdue" ? campaigns.filter((c) => c.status === "overdue") : tab === "completed" ? campaigns.filter((c) => c.status === "completed") : tab === "my-reviews" ? campaigns.filter((c) => c.items.some((i) => i.decision === "pending")) : campaigns, [campaigns, tab])
  async function create() { const reviewerId = Number(form.reviewerId); if (!form.name.trim() || !reviewerId || !form.dueAt) return toast.error("Name, reviewer, and due date are required"); const res = await fetch("/api/admin/security/access-reviews", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, reviewerId, items: users.map((u) => ({ scope: "users", subjectId: u.id, subjectName: u.name, subjectEmail: u.email, access: u.role })) }) }); const body = await res.json(); if (!res.ok) return toast.error(body.error); toast.success("Review campaign created"); setCreateOpen(false); setForm({ ...form, name: "", dueAt: "" }); mutate() }
  async function decide(itemId: number, decision: string) { const comment = decision === "remediated" ? window.prompt("Describe the remediation") ?? "" : ""; const res = await fetch("/api/admin/security/access-reviews", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ itemId, decision, comment }) }); const body = await res.json(); if (!res.ok) return toast.error(body.error); toast.success(`Access ${decision}`); mutate(); setActive((current) => current ? { ...current, items: current.items.map((i) => i.id === itemId ? { ...i, decision, comment } : i) } : null) }
  return <Card><CardHeader className="flex flex-row flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">Access review campaigns</CardTitle><CardDescription>Periodic certification across users, roles, permissions, and non-human access.</CardDescription></div><Button size="sm" onClick={() => setCreateOpen(true)}><Plus data-icon="inline-start" /> Create campaign</Button></CardHeader><CardContent className="flex flex-col gap-4">{error && <p className="text-sm text-destructive">{error.message}</p>}{isLoading ? <p className="text-sm text-muted-foreground">Loading review campaigns…</p> : <Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="my-reviews">Open</TabsTrigger><TabsTrigger value="overdue">Overdue {campaigns.filter((c) => c.status === "overdue").length > 0 && <Badge variant="destructive" className="ml-1">{campaigns.filter((c) => c.status === "overdue").length}</Badge>}</TabsTrigger><TabsTrigger value="completed">Completed</TabsTrigger></TabsList>{["all", "my-reviews", "overdue", "completed"].map((value) => <TabsContent key={value} value={value}><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Campaign</TableHead><TableHead>Reviewer</TableHead><TableHead>Due</TableHead><TableHead>Progress</TableHead><TableHead>Status</TableHead><TableHead /></TableRow></TableHeader><TableBody>{visible.length === 0 ? <TableRow><TableCell colSpan={6} className="py-10 text-center text-sm text-muted-foreground"><ClipboardCheck className="mx-auto mb-2 size-5" />No campaigns in this view.</TableCell></TableRow> : visible.map((c) => { const done = c.items.filter((i) => i.decision !== "pending").length; return <TableRow key={c.id}><TableCell className="font-medium">{c.name}<div className="text-xs text-muted-foreground">{c.items.length} access items</div></TableCell><TableCell>{c.reviewerName ?? "Assigned reviewer"}</TableCell><TableCell className={c.status === "overdue" ? "font-medium text-destructive" : "text-muted-foreground"}>{new Date(c.dueAt).toLocaleDateString()}</TableCell><TableCell className="min-w-32"><Progress value={c.items.length ? done / c.items.length * 100 : 0} /><span className="text-xs text-muted-foreground">{done}/{c.items.length} reviewed</span></TableCell><TableCell>{c.status === "overdue" ? <Badge variant="destructive"><AlertTriangle data-icon="inline-start" />Overdue</Badge> : c.status === "completed" ? <Badge variant="secondary">Completed</Badge> : <Badge variant="outline">Open</Badge>}</TableCell><TableCell className="text-right"><Button variant="outline" size="sm" onClick={() => setActive(c)}>Review</Button></TableCell></TableRow> })}</TableBody></Table></div></TabsContent>)}</Tabs>}</CardContent>
    <Dialog open={Boolean(active)} onOpenChange={(open) => !open && setActive(null)}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{active?.name}</DialogTitle><DialogDescription>Review each access item. Decisions are audited and scoped to this tenant.</DialogDescription></DialogHeader><div className="max-h-[60vh] overflow-y-auto"><Table><TableHeader><TableRow><TableHead>Subject</TableHead><TableHead>Scope</TableHead><TableHead>Access</TableHead><TableHead>Decision</TableHead><TableHead /></TableRow></TableHeader><TableBody>{active?.items.map((i) => <TableRow key={i.id}><TableCell className="font-medium">{i.subjectName}<div className="text-xs text-muted-foreground">{i.subjectEmail}</div></TableCell><TableCell>{scopeLabels[i.scope] ?? i.scope}</TableCell><TableCell>{i.access}</TableCell><TableCell>{i.decision === "pending" ? <Badge variant="outline">Pending</Badge> : <Badge variant="secondary">{i.decision}</Badge>}</TableCell><TableCell className="text-right">{i.decision === "pending" && <div className="flex justify-end gap-1"><Button size="sm" variant="outline" onClick={() => decide(i.id, "approved")}><Check data-icon="inline-start" />Approve</Button><Button size="sm" variant="outline" onClick={() => decide(i.id, "remediated")}><ShieldAlert data-icon="inline-start" />Remediate</Button><Button size="sm" variant="destructive" onClick={() => decide(i.id, "revoked")}><X data-icon="inline-start" />Revoke</Button></div>}</TableCell></TableRow>)}</TableBody></Table></div></DialogContent></Dialog>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Create access review</DialogTitle><DialogDescription>Capture a tenant-scoped snapshot and assign an accountable reviewer.</DialogDescription></DialogHeader><div className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label htmlFor="review-name">Campaign name</Label><Input id="review-name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Q4 privileged access review" /></div><div className="grid gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label>Reviewer</Label><Select value={form.reviewerId} onValueChange={(reviewerId) => setForm({ ...form, reviewerId })}><SelectTrigger><SelectValue placeholder="Select reviewer" /></SelectTrigger><SelectContent>{users.map((u) => <SelectItem key={u.id} value={String(u.id)}>{u.name} · {u.role}</SelectItem>)}</SelectContent></Select></div><div className="flex flex-col gap-2"><Label>Recurrence</Label><Select value={form.recurrence} onValueChange={(recurrence) => setForm({ ...form, recurrence })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["one_time", "monthly", "quarterly", "annually"].map((r) => <SelectItem key={r} value={r}>{r.replace("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="flex flex-col gap-2"><Label htmlFor="review-start">Start</Label><Input id="review-start" type="datetime-local" value={form.startAt} onChange={(e) => setForm({ ...form, startAt: e.target.value })} /></div><div className="flex flex-col gap-2"><Label htmlFor="review-due">Due</Label><Input id="review-due" type="datetime-local" value={form.dueAt} onChange={(e) => setForm({ ...form, dueAt: e.target.value })} /></div></div><p className="text-xs text-muted-foreground">This campaign includes {users.length} active directory users. Additional scopes can be added to the snapshot API.</p></div><DialogFooter><Button variant="outline" onClick={() => setCreateOpen(false)}>Cancel</Button><Button onClick={create}>Create review</Button></DialogFooter></DialogContent></Dialog>
  </Card>
}
